Linux support for message passing
SlimeVR/SlimeVR-OpenVR-Driver pull request #27
Opened 2022-08-18 05:52 UTC by funnbot

Response to #2 
Re implements bridge message passing with unix sockets, a bit more complicated than it should be due to being non-blocking, and it may have been a better idea to use boost.asio, as that would allow the switch to websockets to be seamless..
I tested the best I could with compiler explorer, surprisingly local sockets work there... https://godbolt.org/z/9adEWxdqh
I set the socket path is `/tmp/SlimeVRDriver` as it doesn't require root to write to.

This pr also fixes cmake builds for linux, adds ubuntu-latest to the github action matrix, and uploads the artifact.
Once someone begins work on the Java side, they can download it and hopefully be able to test them together.

I'm funnbot#8284 on the slimevr discord if you have questions.

2022-09-04 01:40 UTC, kitlith commented
Is there anything available to test against this build of the driver, such as a corresponding PR to slimevr-server?

2022-09-11 02:46 UTC, kitlith commented
yeah, i missed the "Once someone begins work on the Java side", my bad.

2022-11-25 03:54 UTC, Eirenliel commented
Please rebase to main and fix confclits. Also we need testing with https://github.com/SlimeVR/SlimeVR-Server/pull/273

2022-11-30 02:37 UTC, ImUrX requested changes
it seems the CMake script generates an ``SlimeVR`` folder instead of using the existing ``slimevr`` one. Surely this bug wasn't noticed before because NTFS isnt case-sensitive, but most linux filesystems are by default

2022-11-30 02:44 UTC, ImUrX requested changes

2022-11-30 02:44 UTC, ImUrX commented on src/bridge/unix-sockets.hpp
> +                         sType = SOCK_SEQPACKET, // message boundaries and connection oriented
Change to SOCK_STREAM

2022-12-02 21:24 UTC, ImUrX commented
now there are more errors, it wont compile for linux because of the ``#ELIF`` in the openvr.cpp

will wait for fix and try after :3

2023-01-15 09:12 UTC, ImUrX approved these changes

2023-01-18 19:16 UTC, Eirenliel approved these changes

2023-01-18 19:17 UTC, merged